import type { Metadata } from "next";
import "./globals.scss";
import ReduxProvider from "@/provider/ReduxProvider";
import { Orbitron } from "next/font/google";

const orbitron = Orbitron({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "KShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={orbitron.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
